esphome:
  name: nibegw
  comment: Nibegw

esp32:
  board: mhetesp32devkit
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret nibegw_ip
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nibegw Fallback Hotspot"
    password: !secret ap_password

web_server:
  port: 80

external_components:
  - source: 
      type: git
      url: https://github.com/elupus/esphome-nibe.git
    components: [ nibegw ]

nibegw:
  dir_pin: GPIO23
  rx_pin: GPIO21
  tx_pin: GPIO22
  udp:
    # The target address(s) to send data to. May be a multicast address.
    target:
      - ip: !secret hass_ip
        port: 10090

    # List of source address to accept data from, may be empty for no filter
    source:
      - !secret hass_ip
      #default read port = 9999;
      #default write port = 10000;

  acknowledge:
    - MODBUS40

  # Constant replies to certain requests can be made
  constants:
    - address: MODBUS40
      token: ACCESSORY
      data: [
            0x0A, # MODBUS version low
            0x00, # MODBUS version high
            0x01, # MODBUS address 1 for F1245
      ]

# Some helper functions to restart ESPHome from HA
button:
- platform: restart
  name: Nibegw Restart
- platform: safe_mode
  name: Nibegw Safe Mode Boot
